### ISSUE TITLE
Have you ever tried training the model with AMP?

### ISSUE THREAD

**Issue by zAuk000** [hongfz16/EVA3D#13] opened 2023-03-20 14:33 UTC
Hi, I think it is a nice work on 3D-Human image generation, so I want to learn more details about the model, but the memory of the graphics card is small so that I try to train the model with AMP (automatic mixed-precision) according to pytorch tutorial, and some problems occurred :
File "/home/xxx/eva3d/op/fused_act.py", line 70, in forward
    out = fused.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
RuntimeError: expected scalar type Half but found Float
I think the problem is related to fused_bias_act.cpp but I dont know how to deal with it，couldn‘t appreciate it more if you could give me some advice

**Comment by hongfz16** [comment] 2023-04-06 12:32
Sorry that I have not tried to use AMP here. The module in the problem is a custom one borrowed from StyleGAN. I guess you might need to implement AMP for this module by yourself. Or you may go checkout the StyleGAN community to see if anyone ever tried this.

Closing. Feel free to reopen it if you have further questions.

**Closed by hongfz16** 2023-04-06 12:32 UTC
